import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className="bg-gradient-to-br from-blue-50 to-blue-100 min-h-screen flex flex-col">
                <header className="bg-white shadow-md py-4 px-6 border-b border-blue-200">
                    <div className="max-w-6xl mx-auto flex items-center justify-between">
                        <h1 className="text-xl font-semibold text-blue-700">Bitrix App</h1>
                        {/* Bạn có thể thêm icon/logout button tại đây nếu cần */}
                        <nav>
                            <Link
                                href="/auth/login"
                                className="text-blue-600 font-medium hover:underline hover:text-blue-800 transition duration-200"
                            >
                                Login
                            </Link>
                        </nav>
                    </div>
                </header>

                <main className="flex-1 flex items-center justify-center px-4 py-8">
                    <div className="w-full max-w-3xl">{children}</div>
                </main>

                <footer className="text-center text-sm text-gray-500 py-4">© {new Date().getFullYear()} Bitrix App. All rights reserved.</footer>
            </body>
        </html>
    );
}
