import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import ROUTE from '@/config/routes';
import QueryClientProviderComp from '@/components/hooks/QueryClientProviderComp';
import Navbar from '@/components/layout/Navbar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className="bg-gradient-to-br from-blue-50 to-blue-100 min-h-screen flex flex-col">
                {/* return lại để không phải bọc nhiều */}
                <QueryClientProviderComp>
                    {/* <header className="mt-20"> */}
                    {/* <div className="max-w-6xl mx-auto">
                            <h1 className="text-xl font-semibold text-blue-700">Bitrix App</h1>
                            Bạn có thể thêm icon/logout button tại đây nếu cần
                            <nav className=" flex items-center justify-between">
                                <Link href={ROUTE.SITEMAP_LV1.home.url} className="text-xl font-semibold text-blue-700">
                                    HOME
                                </Link>
                            </nav>
                        </div> */}
                    {/* </header> */}
                    <Navbar />

                    <main className="container mx-auto mt-16">
                        <div className="w-full">{children}</div>
                    </main>

                    <footer className="text-center text-sm text-gray-500 py-4">© {new Date().getFullYear()} xuanhieu.bitrix24.vn</footer>
                </QueryClientProviderComp>
            </body>
        </html>
    );
}
